//
// File generated by rootcint at Wed Jul 16 23:04:06 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME ItemSelectorDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ItemSelectorDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void ItemSelector_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_ItemSelector(void *p);
   static void deleteArray_ItemSelector(void *p);
   static void destruct_ItemSelector(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ItemSelector*)
   {
      ::ItemSelector *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ItemSelector >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ItemSelector", ::ItemSelector::Class_Version(), "./ItemSelector.h", 25,
                  typeid(::ItemSelector), DefineBehavior(ptr, ptr),
                  &::ItemSelector::Dictionary, isa_proxy, 4,
                  sizeof(::ItemSelector) );
      instance.SetDelete(&delete_ItemSelector);
      instance.SetDeleteArray(&deleteArray_ItemSelector);
      instance.SetDestructor(&destruct_ItemSelector);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ItemSelector*)
   {
      return GenerateInitInstanceLocal((::ItemSelector*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ItemSelector*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *ItemSelector::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *ItemSelector::Class_Name()
{
   return "ItemSelector";
}

//______________________________________________________________________________
const char *ItemSelector::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ItemSelector*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int ItemSelector::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ItemSelector*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void ItemSelector::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ItemSelector*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *ItemSelector::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ItemSelector*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void ItemSelector::Streamer(TBuffer &R__b)
{
   // Stream an object of class ItemSelector.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(ItemSelector::Class(),this);
   } else {
      R__b.WriteClassBuffer(ItemSelector::Class(),this);
   }
}

//______________________________________________________________________________
void ItemSelector::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ItemSelector.
      TClass *R__cl = ::ItemSelector::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pListBox", &pListBox);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pTextEntry", &pTextEntry);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "canceled", &canceled);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_ItemSelector(void *p) {
      delete ((::ItemSelector*)p);
   }
   static void deleteArray_ItemSelector(void *p) {
      delete [] ((::ItemSelector*)p);
   }
   static void destruct_ItemSelector(void *p) {
      typedef ::ItemSelector current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::ItemSelector

/********************************************************
* ItemSelectorDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableItemSelectorDict();

extern "C" void G__set_cpp_environmentItemSelectorDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("ItemSelector.h");
  G__cpp_reset_tagtableItemSelectorDict();
}
#include <new>
extern "C" int G__cpp_dllrevItemSelectorDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ItemSelector */
static int G__ItemSelectorDict_639_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ItemSelector* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new ItemSelector(
*(vector<pair<string,bool> >*) libp->para[0].ref, *(bool*) G__Boolref(&libp->para[1])
, *(string*) libp->para[2].ref);
   } else {
     p = new((void*) gvp) ItemSelector(
*(vector<pair<string,bool> >*) libp->para[0].ref, *(bool*) G__Boolref(&libp->para[1])
, *(string*) libp->para[2].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ItemSelectorDictLN_ItemSelector));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ItemSelectorDict_639_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ItemSelector*) G__getstructoffset())->Select();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ItemSelectorDict_639_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ItemSelector*) G__getstructoffset())->Close();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ItemSelectorDict_639_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ItemSelector*) G__getstructoffset())->InvertSelection();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ItemSelectorDict_639_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ItemSelector*) G__getstructoffset())->Filter((char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ItemSelectorDict_639_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ItemSelector*) G__getstructoffset())->Cancel();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ItemSelectorDict_639_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ItemSelector::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ItemSelectorDict_639_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ItemSelector::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ItemSelectorDict_639_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ItemSelector::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ItemSelectorDict_639_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ItemSelector::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ItemSelectorDict_639_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ItemSelector*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ItemSelectorDict_639_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ItemSelector::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ItemSelectorDict_639_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ItemSelector::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ItemSelectorDict_639_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ItemSelector::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ItemSelectorDict_639_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ItemSelector::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ItemSelector G__TItemSelector;
static int G__ItemSelectorDict_639_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ItemSelector*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ItemSelector*) (soff+(sizeof(ItemSelector)*i)))->~G__TItemSelector();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ItemSelector*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ItemSelector*) (soff))->~G__TItemSelector();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ItemSelector */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncItemSelectorDict {
 public:
  G__Sizep2memfuncItemSelectorDict(): p(&G__Sizep2memfuncItemSelectorDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncItemSelectorDict::*p)();
};

size_t G__get_sizep2memfuncItemSelectorDict()
{
  G__Sizep2memfuncItemSelectorDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceItemSelectorDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ItemSelectorDictLN_ItemSelector))) {
     ItemSelector *G__Lderived;
     G__Lderived=(ItemSelector*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ItemSelectorDictLN_ItemSelector),G__get_linked_tagnum(&G__ItemSelectorDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ItemSelectorDictLN_ItemSelector),G__get_linked_tagnum(&G__ItemSelectorDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ItemSelectorDictLN_ItemSelector),G__get_linked_tagnum(&G__ItemSelectorDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ItemSelectorDictLN_ItemSelector),G__get_linked_tagnum(&G__ItemSelectorDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ItemSelectorDictLN_ItemSelector),G__get_linked_tagnum(&G__ItemSelectorDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ItemSelectorDictLN_ItemSelector),G__get_linked_tagnum(&G__ItemSelectorDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ItemSelectorDictLN_ItemSelector),G__get_linked_tagnum(&G__ItemSelectorDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableItemSelectorDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<string,bool> >",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlEpairlEstringcOboolgRcOallocatorlEpairlEstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlEpairlEstringcOboolgRcOallocatorlEpairlEstringcOboolgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlEpairlEstringcOboolgRcOallocatorlEpairlEstringcOboolgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlEpairlEstringcOboolgRcOallocatorlEpairlEstringcOboolgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlEpairlEstringcOboolgRcOallocatorlEpairlEstringcOboolgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ItemSelector */
static void G__setup_memvarItemSelector(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ItemSelectorDictLN_ItemSelector));
   { ItemSelector *p; p=(ItemSelector*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,1,0,G__get_linked_tagnum(&G__ItemSelectorDictLN_vectorlEpairlEstringcOboolgRcOallocatorlEpairlEstringcOboolgRsPgRsPgR),G__defined_typename("vector<pair<string,bool> >"),-1,4,"items=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ItemSelectorDictLN_TGListBox),-1,-1,4,"pListBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ItemSelectorDictLN_TGTextEntry),-1,-1,4,"pTextEntry=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,1,0,-1,-1,-1,4,"canceled=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ItemSelectorDictLN_TApplication),-1,-2,4,"pApp=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ItemSelectorDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)(&ItemSelector::wid),105,0,0,-1,-1,-2,1,"wid=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarItemSelectorDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncItemSelector(void) {
   /* ItemSelector */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ItemSelectorDictLN_ItemSelector));
   G__memfunc_setup("ItemSelector",1232,G__ItemSelectorDict_639_0_1, 105, G__get_linked_tagnum(&G__ItemSelectorDictLN_ItemSelector), -1, 0, 3, 1, 1, 0, 
"u 'vector<pair<string,bool>,allocator<pair<string,bool> > >' 'vector<pair<string,bool> >' 1 - items g - - 1 - canceled "
"u 'string' - 11 - title", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Select",608,G__ItemSelectorDict_639_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Close",502,G__ItemSelectorDict_639_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InvertSelection",1566,G__ItemSelectorDict_639_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Filter",614,G__ItemSelectorDict_639_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 0 - str", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Cancel",582,G__ItemSelectorDict_639_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ItemSelectorDict_639_0_7, 85, G__get_linked_tagnum(&G__ItemSelectorDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ItemSelector::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ItemSelectorDict_639_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ItemSelector::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ItemSelectorDict_639_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ItemSelector::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ItemSelectorDict_639_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ItemSelector::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ItemSelectorDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ItemSelectorDict_639_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ItemSelectorDict_639_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ItemSelector::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ItemSelectorDict_639_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ItemSelector::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ItemSelectorDict_639_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ItemSelector::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ItemSelectorDict_639_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ItemSelector::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~ItemSelector", 1358, G__ItemSelectorDict_639_0_19, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncItemSelectorDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
   G__memvar_setup((void*)G__PVOID,112,0,0,-1,-1,-1,1,"ITEMSELECTOR_H=0",1,(char*)NULL);
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalItemSelectorDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcItemSelectorDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ItemSelectorDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_TApplication = { "TApplication" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_TGListBox = { "TGListBox" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_TGTextEntry = { "TGTextEntry" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_ItemSelector = { "ItemSelector" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_vectorlEpairlEstringcOboolgRcOallocatorlEpairlEstringcOboolgRsPgRsPgR = { "vector<pair<string,bool>,allocator<pair<string,bool> > >" , 99 , -1 };
G__linked_taginfo G__ItemSelectorDictLN_reverse_iteratorlEvectorlEpairlEstringcOboolgRcOallocatorlEpairlEstringcOboolgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<string,bool>,allocator<pair<string,bool> > >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableItemSelectorDict() {
  G__ItemSelectorDictLN_TClass.tagnum = -1 ;
  G__ItemSelectorDictLN_TBuffer.tagnum = -1 ;
  G__ItemSelectorDictLN_TMemberInspector.tagnum = -1 ;
  G__ItemSelectorDictLN_TObject.tagnum = -1 ;
  G__ItemSelectorDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__ItemSelectorDictLN_string.tagnum = -1 ;
  G__ItemSelectorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ItemSelectorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ItemSelectorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ItemSelectorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ItemSelectorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__ItemSelectorDictLN_TApplication.tagnum = -1 ;
  G__ItemSelectorDictLN_TQObject.tagnum = -1 ;
  G__ItemSelectorDictLN_TGWindow.tagnum = -1 ;
  G__ItemSelectorDictLN_TGObject.tagnum = -1 ;
  G__ItemSelectorDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__ItemSelectorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__ItemSelectorDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ItemSelectorDictLN_TGFrame.tagnum = -1 ;
  G__ItemSelectorDictLN_TGCompositeFrame.tagnum = -1 ;
  G__ItemSelectorDictLN_TGMainFrame.tagnum = -1 ;
  G__ItemSelectorDictLN_TGListBox.tagnum = -1 ;
  G__ItemSelectorDictLN_TGTextEntry.tagnum = -1 ;
  G__ItemSelectorDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__ItemSelectorDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ItemSelectorDictLN_ItemSelector.tagnum = -1 ;
  G__ItemSelectorDictLN_vectorlEpairlEstringcOboolgRcOallocatorlEpairlEstringcOboolgRsPgRsPgR.tagnum = -1 ;
  G__ItemSelectorDictLN_reverse_iteratorlEvectorlEpairlEstringcOboolgRcOallocatorlEpairlEstringcOboolgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableItemSelectorDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_string);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_TApplication);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_TGListBox);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_TGTextEntry);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_ItemSelector),sizeof(ItemSelector),-1,324608,(char*)NULL,G__setup_memvarItemSelector,G__setup_memfuncItemSelector);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_vectorlEpairlEstringcOboolgRcOallocatorlEpairlEstringcOboolgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ItemSelectorDictLN_reverse_iteratorlEvectorlEpairlEstringcOboolgRcOallocatorlEpairlEstringcOboolgRsPgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupItemSelectorDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupItemSelectorDict()");
  G__set_cpp_environmentItemSelectorDict();
  G__cpp_setup_tagtableItemSelectorDict();

  G__cpp_setup_inheritanceItemSelectorDict();

  G__cpp_setup_typetableItemSelectorDict();

  G__cpp_setup_memvarItemSelectorDict();

  G__cpp_setup_memfuncItemSelectorDict();
  G__cpp_setup_globalItemSelectorDict();
  G__cpp_setup_funcItemSelectorDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncItemSelectorDict();
  return;
}
class G__cpp_setup_initItemSelectorDict {
  public:
    G__cpp_setup_initItemSelectorDict() { G__add_setup_func("ItemSelectorDict",(G__incsetup)(&G__cpp_setupItemSelectorDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initItemSelectorDict() { G__remove_setup_func("ItemSelectorDict"); }
};
G__cpp_setup_initItemSelectorDict G__cpp_setup_initializerItemSelectorDict;

