/********************************************************************
* ItemSelectorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ItemSelectorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableItemSelectorDict();
extern void G__cpp_setup_inheritanceItemSelectorDict();
extern void G__cpp_setup_typetableItemSelectorDict();
extern void G__cpp_setup_memvarItemSelectorDict();
extern void G__cpp_setup_globalItemSelectorDict();
extern void G__cpp_setup_memfuncItemSelectorDict();
extern void G__cpp_setup_funcItemSelectorDict();
extern void G__set_cpp_environmentItemSelectorDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ItemSelector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ItemSelectorDictLN_TClass;
extern G__linked_taginfo G__ItemSelectorDictLN_TBuffer;
extern G__linked_taginfo G__ItemSelectorDictLN_TMemberInspector;
extern G__linked_taginfo G__ItemSelectorDictLN_TObject;
extern G__linked_taginfo G__ItemSelectorDictLN_string;
extern G__linked_taginfo G__ItemSelectorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ItemSelectorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ItemSelectorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ItemSelectorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ItemSelectorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ItemSelectorDictLN_TApplication;
extern G__linked_taginfo G__ItemSelectorDictLN_TQObject;
extern G__linked_taginfo G__ItemSelectorDictLN_TGWindow;
extern G__linked_taginfo G__ItemSelectorDictLN_TGObject;
extern G__linked_taginfo G__ItemSelectorDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__ItemSelectorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__ItemSelectorDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ItemSelectorDictLN_TGFrame;
extern G__linked_taginfo G__ItemSelectorDictLN_TGCompositeFrame;
extern G__linked_taginfo G__ItemSelectorDictLN_TGMainFrame;
extern G__linked_taginfo G__ItemSelectorDictLN_TGListBox;
extern G__linked_taginfo G__ItemSelectorDictLN_ItemSelector;
extern G__linked_taginfo G__ItemSelectorDictLN_vectorlEpairlEintcOstringgRcOallocatorlEpairlEintcOstringgRsPgRsPgR;
extern G__linked_taginfo G__ItemSelectorDictLN_reverse_iteratorlEvectorlEpairlEintcOstringgRcOallocatorlEpairlEintcOstringgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
