//
// File generated by rootcint at Fri Jul 18 00:10:48 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME SelectDialogDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "SelectDialogDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::SelectDialogEntry SelectDialogEntry;
      #else
      class SelectDialogEntry  {
         public:
         //friend XX;
         string text; //
         bool selected; //
         int id; //
      };
      #endif

      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::SelectDialog SelectDialog;
      #else
      class SelectDialog  {
         public:
         //friend XX;
         vector< ::SelectDialogEntry >* entries; //
         bool* cancelled; //
         :: TGWindow* pMainWindow; //
         ::TGTransientFrame* pDialogFrame; //
         ::TGHorizontalFrame* pFrameFilter; //
         ::TGLayoutHints* pLayoutFrameFilter; //
         ::TGLayoutHints* pLayoutLabelFilter; //
         ::TGLayoutHints* pLayoutTextEntryFilter; //
         ::TGLabel* pLabelFilter; //
         ::TGTextEntry* pTextEntryFilter; //
         ::TGListBox* pListBox; //
         ::TGLayoutHints* pLayoutListBox; //
         ::TGHorizontalFrame* pFrameButtons; //
         ::TGHorizontalFrame* pFrameButtons2; //
         ::TGLayoutHints* pLayoutFrameButtons; //
         ::TGLayoutHints* pLayoutButtons; //
         ::TGTextButton* pButtonSelect; //
         ::TGTextButton* pButtonInvert; //
         ::TGTextButton* pButtonSelAll; //
         ::TGTextButton* pButtonCancel; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void SelectDialogEntry_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void SelectDialogEntry_Dictionary();
   static void delete_SelectDialogEntry(void *p);
   static void deleteArray_SelectDialogEntry(void *p);
   static void destruct_SelectDialogEntry(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::SelectDialogEntry*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::SelectDialogEntry) == sizeof(::ROOT::Shadow::SelectDialogEntry));
      ::SelectDialogEntry *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::SelectDialogEntry),0);
      static ::ROOT::TGenericClassInfo 
         instance("SelectDialogEntry", "./SelectDialog.h", 25,
                  typeid(::SelectDialogEntry), DefineBehavior(ptr, ptr),
                  &SelectDialogEntry_ShowMembers, &SelectDialogEntry_Dictionary, isa_proxy, 4,
                  sizeof(::SelectDialogEntry) );
      instance.SetDelete(&delete_SelectDialogEntry);
      instance.SetDeleteArray(&deleteArray_SelectDialogEntry);
      instance.SetDestructor(&destruct_SelectDialogEntry);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::SelectDialogEntry*)
   {
      return GenerateInitInstanceLocal((::SelectDialogEntry*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SelectDialogEntry*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void SelectDialogEntry_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::SelectDialogEntry*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void SelectDialog_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void SelectDialog_Dictionary();
   static void delete_SelectDialog(void *p);
   static void deleteArray_SelectDialog(void *p);
   static void destruct_SelectDialog(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::SelectDialog*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::SelectDialog) == sizeof(::ROOT::Shadow::SelectDialog));
      ::SelectDialog *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::SelectDialog),0);
      static ::ROOT::TGenericClassInfo 
         instance("SelectDialog", "./SelectDialog.h", 39,
                  typeid(::SelectDialog), DefineBehavior(ptr, ptr),
                  &SelectDialog_ShowMembers, &SelectDialog_Dictionary, isa_proxy, 4,
                  sizeof(::SelectDialog) );
      instance.SetDelete(&delete_SelectDialog);
      instance.SetDeleteArray(&deleteArray_SelectDialog);
      instance.SetDestructor(&destruct_SelectDialog);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::SelectDialog*)
   {
      return GenerateInitInstanceLocal((::SelectDialog*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SelectDialog*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void SelectDialog_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::SelectDialog*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void SelectDialogEntry_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class SelectDialogEntry.
      typedef ::ROOT::Shadow::SelectDialogEntry ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::SelectDialogEntry*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "text", (void*)&sobj->text);
      R__insp.InspectMember("string", (void*)&sobj->text, "text.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "selected", &sobj->selected);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "id", &sobj->id);
   }

}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_SelectDialogEntry(void *p) {
      delete ((::SelectDialogEntry*)p);
   }
   static void deleteArray_SelectDialogEntry(void *p) {
      delete [] ((::SelectDialogEntry*)p);
   }
   static void destruct_SelectDialogEntry(void *p) {
      typedef ::SelectDialogEntry current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::SelectDialogEntry

//______________________________________________________________________________
namespace ROOT {
   void SelectDialog_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class SelectDialog.
      typedef ::ROOT::Shadow::SelectDialog ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::SelectDialog*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "cancelled", &sobj->cancelled);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pMainWindow", &sobj->pMainWindow);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pDialogFrame", &sobj->pDialogFrame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pFrameFilter", &sobj->pFrameFilter);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pLayoutFrameFilter", &sobj->pLayoutFrameFilter);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pLayoutLabelFilter", &sobj->pLayoutLabelFilter);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pLayoutTextEntryFilter", &sobj->pLayoutTextEntryFilter);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pLabelFilter", &sobj->pLabelFilter);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pTextEntryFilter", &sobj->pTextEntryFilter);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pListBox", &sobj->pListBox);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pLayoutListBox", &sobj->pLayoutListBox);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pFrameButtons", &sobj->pFrameButtons);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pFrameButtons2", &sobj->pFrameButtons2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pLayoutFrameButtons", &sobj->pLayoutFrameButtons);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pLayoutButtons", &sobj->pLayoutButtons);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pButtonSelect", &sobj->pButtonSelect);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pButtonInvert", &sobj->pButtonInvert);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pButtonSelAll", &sobj->pButtonSelAll);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pButtonCancel", &sobj->pButtonCancel);
   }

}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_SelectDialog(void *p) {
      delete ((::SelectDialog*)p);
   }
   static void deleteArray_SelectDialog(void *p) {
      delete [] ((::SelectDialog*)p);
   }
   static void destruct_SelectDialog(void *p) {
      typedef ::SelectDialog current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::SelectDialog

/********************************************************
* SelectDialogDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableSelectDialogDict();

extern "C" void G__set_cpp_environmentSelectDialogDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("SelectDialog.h");
  G__cpp_reset_tagtableSelectDialogDict();
}
#include <new>
extern "C" int G__cpp_dllrevSelectDialogDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* SelectDialogEntry */
static int G__SelectDialogDict_354_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SelectDialogEntry* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SelectDialogEntry(
*(string*) libp->para[0].ref, (bool) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
     } else {
       p = new((void*) gvp) SelectDialogEntry(
*(string*) libp->para[0].ref, (bool) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
     }
     break;
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SelectDialogEntry(*(string*) libp->para[0].ref, (bool) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) SelectDialogEntry(*(string*) libp->para[0].ref, (bool) G__int(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SelectDialogEntry(*(string*) libp->para[0].ref);
     } else {
       p = new((void*) gvp) SelectDialogEntry(*(string*) libp->para[0].ref);
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SelectDialogDictLN_SelectDialogEntry));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__SelectDialogDict_354_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   SelectDialogEntry* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new SelectDialogEntry(*(SelectDialogEntry*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SelectDialogDictLN_SelectDialogEntry));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SelectDialogEntry G__TSelectDialogEntry;
static int G__SelectDialogDict_354_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SelectDialogEntry*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SelectDialogEntry*) (soff+(sizeof(SelectDialogEntry)*i)))->~G__TSelectDialogEntry();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SelectDialogEntry*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SelectDialogEntry*) (soff))->~G__TSelectDialogEntry();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__SelectDialogDict_354_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SelectDialogEntry* dest = (SelectDialogEntry*) G__getstructoffset();
   *dest = *(SelectDialogEntry*) libp->para[0].ref;
   const SelectDialogEntry& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* SelectDialog */
static int G__SelectDialogDict_355_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SelectDialog* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new SelectDialog(
*(string*) libp->para[0].ref, *(vector<SelectDialogEntry>*) libp->para[1].ref
, *(bool*) G__Boolref(&libp->para[2]));
   } else {
     p = new((void*) gvp) SelectDialog(
*(string*) libp->para[0].ref, *(vector<SelectDialogEntry>*) libp->para[1].ref
, *(bool*) G__Boolref(&libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SelectDialogDictLN_SelectDialog));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SelectDialogDict_355_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SelectDialog*) G__getstructoffset())->Close();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SelectDialogDict_355_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SelectDialog*) G__getstructoffset())->ChangedFilter((char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SelectDialogDict_355_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SelectDialog*) G__getstructoffset())->PressedSelect();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SelectDialogDict_355_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SelectDialog*) G__getstructoffset())->PressedInvert();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SelectDialogDict_355_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SelectDialog*) G__getstructoffset())->PressedSelAll();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SelectDialogDict_355_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SelectDialog*) G__getstructoffset())->PressedCancel();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SelectDialogDict_355_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SelectDialog*) G__getstructoffset())->PressedClose();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__SelectDialogDict_355_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   SelectDialog* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new SelectDialog(*(SelectDialog*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SelectDialogDictLN_SelectDialog));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SelectDialog G__TSelectDialog;
static int G__SelectDialogDict_355_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SelectDialog*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SelectDialog*) (soff+(sizeof(SelectDialog)*i)))->~G__TSelectDialog();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SelectDialog*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SelectDialog*) (soff))->~G__TSelectDialog();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* SelectDialogEntry */

/* SelectDialog */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncSelectDialogDict {
 public:
  G__Sizep2memfuncSelectDialogDict(): p(&G__Sizep2memfuncSelectDialogDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncSelectDialogDict::*p)();
};

size_t G__get_sizep2memfuncSelectDialogDict()
{
  G__Sizep2memfuncSelectDialogDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceSelectDialogDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableSelectDialogDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SelectDialogEntry>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlESelectDialogEntrycOallocatorlESelectDialogEntrygRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_reverse_iteratorlEvectorlESelectDialogEntrycOallocatorlESelectDialogEntrygRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlESelectDialogEntrycOallocatorlESelectDialogEntrygRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SelectDialogDictLN_reverse_iteratorlEvectorlESelectDialogEntrycOallocatorlESelectDialogEntrygRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlESelectDialogEntrycOallocatorlESelectDialogEntrygRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* SelectDialogEntry */
static void G__setup_memvarSelectDialogEntry(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__SelectDialogDictLN_SelectDialogEntry));
   { SelectDialogEntry *p; p=(SelectDialogEntry*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->text)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_string),-1,-1,1,"text=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->selected)-(long)(p)),103,0,0,-1,-1,-1,1,"selected=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->id)-(long)(p)),105,0,0,-1,-1,-1,1,"id=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* SelectDialog */
static void G__setup_memvarSelectDialog(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__SelectDialogDictLN_SelectDialog));
   { SelectDialog *p; p=(SelectDialog*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,1,0,G__get_linked_tagnum(&G__SelectDialogDictLN_vectorlESelectDialogEntrycOallocatorlESelectDialogEntrygRsPgR),G__defined_typename("vector<SelectDialogEntry>"),-1,4,"entries=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,1,0,-1,-1,-1,4,"cancelled=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,1,G__get_linked_tagnum(&G__SelectDialogDictLN_TGWindow),-1,-1,4,"pMainWindow=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGTransientFrame),-1,-1,4,"pDialogFrame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGHorizontalFrame),-1,-1,4,"pFrameFilter=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGLayoutHints),-1,-1,4,"pLayoutFrameFilter=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGLayoutHints),-1,-1,4,"pLayoutLabelFilter=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGLayoutHints),-1,-1,4,"pLayoutTextEntryFilter=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGLabel),-1,-1,4,"pLabelFilter=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGTextEntry),-1,-1,4,"pTextEntryFilter=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGListBox),-1,-1,4,"pListBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGLayoutHints),-1,-1,4,"pLayoutListBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGHorizontalFrame),-1,-1,4,"pFrameButtons=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGHorizontalFrame),-1,-1,4,"pFrameButtons2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGLayoutHints),-1,-1,4,"pLayoutFrameButtons=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGLayoutHints),-1,-1,4,"pLayoutButtons=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGTextButton),-1,-1,4,"pButtonSelect=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGTextButton),-1,-1,4,"pButtonInvert=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGTextButton),-1,-1,4,"pButtonSelAll=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SelectDialogDictLN_TGTextButton),-1,-1,4,"pButtonCancel=",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,104,0,1,-1,-1,-2,4,"default_width=0ULL",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,104,0,1,-1,-1,-2,4,"default_height=0ULL",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-2,4,"prev_flag=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-2,4,"prev_x=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-2,4,"prev_y=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-2,4,"prev_width=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-2,4,"prev_height=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-2,4,"map_offset_x=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-2,4,"map_offset_y=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarSelectDialogDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSelectDialogEntry(void) {
   /* SelectDialogEntry */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__SelectDialogDictLN_SelectDialogEntry));
   G__memfunc_setup("SelectDialogEntry",1730,G__SelectDialogDict_354_0_1, 105, G__get_linked_tagnum(&G__SelectDialogDictLN_SelectDialogEntry), -1, 0, 3, 1, 1, 0, 
"u 'string' - 11 - text g - - 0 'false' selected "
"i - - 0 '0' id", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("SelectDialogEntry", 1730, G__SelectDialogDict_354_0_2, (int) ('i'), G__get_linked_tagnum(&G__SelectDialogDictLN_SelectDialogEntry), -1, 0, 1, 1, 1, 0, "u 'SelectDialogEntry' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~SelectDialogEntry", 1856, G__SelectDialogDict_354_0_3, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__SelectDialogDict_354_0_4, (int) ('u'), G__get_linked_tagnum(&G__SelectDialogDictLN_SelectDialogEntry), -1, 1, 1, 1, 1, 0, "u 'SelectDialogEntry' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncSelectDialog(void) {
   /* SelectDialog */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__SelectDialogDictLN_SelectDialog));
   G__memfunc_setup("SelectDialog",1200,G__SelectDialogDict_355_0_1, 105, G__get_linked_tagnum(&G__SelectDialogDictLN_SelectDialog), -1, 0, 3, 1, 1, 0, 
"u 'string' - 11 - title u 'vector<SelectDialogEntry,allocator<SelectDialogEntry> >' 'vector<SelectDialogEntry>' 1 - entries "
"g - - 1 - cancelled", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Close",502,G__SelectDialogDict_355_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangedFilter",1296,G__SelectDialogDict_355_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 0 - cstr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PressedSelect",1334,G__SelectDialogDict_355_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PressedInvert",1358,G__SelectDialogDict_355_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PressedSelAll",1299,G__SelectDialogDict_355_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PressedCancel",1308,G__SelectDialogDict_355_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PressedClose",1228,G__SelectDialogDict_355_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PositionWindow",1485,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Cleanup",712,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DelayedClose",1198,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("SelectDialog", 1200, G__SelectDialogDict_355_0_12, (int) ('i'), G__get_linked_tagnum(&G__SelectDialogDictLN_SelectDialog), -1, 0, 1, 1, 1, 0, "u 'SelectDialog' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~SelectDialog", 1326, G__SelectDialogDict_355_0_13, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncSelectDialogDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
   G__memvar_setup((void*)G__PVOID,112,0,0,-1,-1,-1,1,"_SELECTDIALOG_H=0",1,(char*)NULL);
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalSelectDialogDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcSelectDialogDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__SelectDialogDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__SelectDialogDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_TGLayoutHints = { "TGLayoutHints" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__SelectDialogDictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_TGHorizontalFrame = { "TGHorizontalFrame" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_TGTransientFrame = { "TGTransientFrame" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_TGTextEntry = { "TGTextEntry" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_TGLabel = { "TGLabel" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_TGListBox = { "TGListBox" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_SelectDialogEntry = { "SelectDialogEntry" , 115 , -1 };
G__linked_taginfo G__SelectDialogDictLN_SelectDialog = { "SelectDialog" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_vectorlESelectDialogEntrycOallocatorlESelectDialogEntrygRsPgR = { "vector<SelectDialogEntry,allocator<SelectDialogEntry> >" , 99 , -1 };
G__linked_taginfo G__SelectDialogDictLN_reverse_iteratorlEvectorlESelectDialogEntrycOallocatorlESelectDialogEntrygRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SelectDialogEntry,allocator<SelectDialogEntry> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableSelectDialogDict() {
  G__SelectDialogDictLN_string.tagnum = -1 ;
  G__SelectDialogDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__SelectDialogDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SelectDialogDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__SelectDialogDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SelectDialogDictLN_TGWindow.tagnum = -1 ;
  G__SelectDialogDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__SelectDialogDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__SelectDialogDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SelectDialogDictLN_TGLayoutHints.tagnum = -1 ;
  G__SelectDialogDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__SelectDialogDictLN_TGTextButton.tagnum = -1 ;
  G__SelectDialogDictLN_TGHorizontalFrame.tagnum = -1 ;
  G__SelectDialogDictLN_TGTransientFrame.tagnum = -1 ;
  G__SelectDialogDictLN_TGTextEntry.tagnum = -1 ;
  G__SelectDialogDictLN_TGLabel.tagnum = -1 ;
  G__SelectDialogDictLN_TGListBox.tagnum = -1 ;
  G__SelectDialogDictLN_SelectDialogEntry.tagnum = -1 ;
  G__SelectDialogDictLN_SelectDialog.tagnum = -1 ;
  G__SelectDialogDictLN_vectorlESelectDialogEntrycOallocatorlESelectDialogEntrygRsPgR.tagnum = -1 ;
  G__SelectDialogDictLN_reverse_iteratorlEvectorlESelectDialogEntrycOallocatorlESelectDialogEntrygRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableSelectDialogDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_string);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_TGLayoutHints);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_TGHorizontalFrame);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_TGTransientFrame);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_TGTextEntry);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_TGLabel);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_TGListBox);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_SelectDialogEntry),sizeof(SelectDialogEntry),-1,294912,(char*)NULL,G__setup_memvarSelectDialogEntry,G__setup_memfuncSelectDialogEntry);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_SelectDialog),sizeof(SelectDialog),-1,295936,(char*)NULL,G__setup_memvarSelectDialog,G__setup_memfuncSelectDialog);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_vectorlESelectDialogEntrycOallocatorlESelectDialogEntrygRsPgR);
   G__get_linked_tagnum_fwd(&G__SelectDialogDictLN_reverse_iteratorlEvectorlESelectDialogEntrycOallocatorlESelectDialogEntrygRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupSelectDialogDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupSelectDialogDict()");
  G__set_cpp_environmentSelectDialogDict();
  G__cpp_setup_tagtableSelectDialogDict();

  G__cpp_setup_inheritanceSelectDialogDict();

  G__cpp_setup_typetableSelectDialogDict();

  G__cpp_setup_memvarSelectDialogDict();

  G__cpp_setup_memfuncSelectDialogDict();
  G__cpp_setup_globalSelectDialogDict();
  G__cpp_setup_funcSelectDialogDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncSelectDialogDict();
  return;
}
class G__cpp_setup_initSelectDialogDict {
  public:
    G__cpp_setup_initSelectDialogDict() { G__add_setup_func("SelectDialogDict",(G__incsetup)(&G__cpp_setupSelectDialogDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initSelectDialogDict() { G__remove_setup_func("SelectDialogDict"); }
};
G__cpp_setup_initSelectDialogDict G__cpp_setup_initializerSelectDialogDict;

