CXXFLAGS=-Wall -O2 -g $(shell root-config --cflags)
LDLIBS=$(shell root-config --libs) 

all: Eff_B2JpsiKstar Eff_B2KstarMuMu Eff_B2LambdaMuMu

Eff_B2JpsiKstar: Eff_B2JpsiKstar.cpp
Eff_B2KstarMuMu: Eff_B2KstarMuMu.cpp
Eff_B2LambdMuMu: Eff_B2LambdaMuMu.cpp
