CXXFLAGS=-Wall -O2 -g $(shell root-config --cflags)
LDLIBS=$(shell root-config --libs) 

all: Changeparticle Changeparticle_afterBDT Changeparticle_SignalMC

Changeparticle: Changeparticle.cpp
Changeparticle_afterBDT: Changeparticle_afterBDT.cpp
Changeparticle_SignalMC: Changeparticle_SignalMC.cpp
