/********************************************************************
* SelectDialogDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SelectDialogDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSelectDialogDict();
extern void G__cpp_setup_inheritanceSelectDialogDict();
extern void G__cpp_setup_typetableSelectDialogDict();
extern void G__cpp_setup_memvarSelectDialogDict();
extern void G__cpp_setup_globalSelectDialogDict();
extern void G__cpp_setup_memfuncSelectDialogDict();
extern void G__cpp_setup_funcSelectDialogDict();
extern void G__set_cpp_environmentSelectDialogDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SelectDialog.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SelectDialogDictLN_string;
extern G__linked_taginfo G__SelectDialogDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SelectDialogDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SelectDialogDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SelectDialogDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SelectDialogDictLN_TGWindow;
extern G__linked_taginfo G__SelectDialogDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__SelectDialogDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__SelectDialogDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SelectDialogDictLN_TGLayoutHints;
extern G__linked_taginfo G__SelectDialogDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SelectDialogDictLN_TGTextButton;
extern G__linked_taginfo G__SelectDialogDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__SelectDialogDictLN_TGTransientFrame;
extern G__linked_taginfo G__SelectDialogDictLN_TGTextEntry;
extern G__linked_taginfo G__SelectDialogDictLN_TGLabel;
extern G__linked_taginfo G__SelectDialogDictLN_TGListBox;
extern G__linked_taginfo G__SelectDialogDictLN_SelectDialogEntry;
extern G__linked_taginfo G__SelectDialogDictLN_SelectDialog;
extern G__linked_taginfo G__SelectDialogDictLN_vectorlESelectDialogEntrycOallocatorlESelectDialogEntrygRsPgR;
extern G__linked_taginfo G__SelectDialogDictLN_reverse_iteratorlEvectorlESelectDialogEntrycOallocatorlESelectDialogEntrygRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
